2023-04-15 22:31:47 MainThread:8597308096 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-15 22:31:47 MainThread:8597308096 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-15 22:31:47 MainThread:8597308096 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-15 22:32:27 MainThread:8607015616 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-15 22:32:27 MainThread:8607015616 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-15 22:32:27 MainThread:8607015616 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:29:30 MainThread:8593998528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:29:30 MainThread:8593998528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:29:30 MainThread:8593998528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:29:55 MainThread:8660984512 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:29:55 MainThread:8660984512 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:29:55 MainThread:8660984512 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:30:10 MainThread:8674542272 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:30:10 MainThread:8674542272 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-16 21:30:10 MainThread:8674542272 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:37] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:16:47 MainThread:8635740864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:68] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:16:47 MainThread:8635740864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:68] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:16:47 MainThread:8635740864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:68] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:21:18 MainThread:8676479680 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:21:18 MainThread:8676479680 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:21:18 MainThread:8676479680 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:23:00 MainThread:8669868736 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:23:00 MainThread:8669868736 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:23:00 MainThread:8669868736 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:28:14 MainThread:8664371904 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:28:14 MainThread:8664371904 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:28:14 MainThread:8664371904 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:29:10 MainThread:8662717120 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:29:10 MainThread:8662717120 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:29:10 MainThread:8662717120 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:29:13 MainThread:8662717120 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:29:13 MainThread:8662717120 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:29:13 MainThread:8662717120 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:11 MainThread:8638415552 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:11 MainThread:8638415552 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:11 MainThread:8638415552 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:35 MainThread:8605328064 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:35 MainThread:8605328064 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:35 MainThread:8605328064 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:39 MainThread:8605328064 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:39 MainThread:8605328064 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:30:39 MainThread:8605328064 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:33:45 MainThread:8630678208 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:33:45 MainThread:8630678208 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:33:45 MainThread:8630678208 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:34:16 MainThread:8598364864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:34:16 MainThread:8598364864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:34:16 MainThread:8598364864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:34:21 MainThread:8598364864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:34:21 MainThread:8598364864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:34:21 MainThread:8598364864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:40:39 MainThread:8628716224 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:40:39 MainThread:8628716224 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:40:39 MainThread:8628716224 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:40:43 MainThread:8628716224 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:40:43 MainThread:8628716224 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:40:43 MainThread:8628716224 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:53:20 MainThread:8635282112 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:53:20 MainThread:8635282112 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:53:20 MainThread:8635282112 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:55:09 MainThread:8598414016 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:55:09 MainThread:8598414016 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:55:09 MainThread:8598414016 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 20:58:56 MainThread:8628220608 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-04-19 20:58:56 MainThread:8628220608 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-04-19 20:58:56 MainThread:8628220608 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-04-19 20:59:00 MainThread:8628220608 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-04-19 20:59:00 MainThread:8628220608 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-04-19 20:59:00 MainThread:8628220608 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-04-19 20:59:07 MainThread:8604451520 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-04-19 20:59:07 MainThread:8604451520 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-04-19 20:59:07 MainThread:8604451520 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-04-19 20:59:10 MainThread:8604451520 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-04-19 20:59:10 MainThread:8604451520 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-04-19 20:59:10 MainThread:8604451520 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-04-19 21:02:58 MainThread:8675099328 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-04-19 21:02:58 MainThread:8675099328 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-04-19 21:02:58 MainThread:8675099328 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-04-19 21:03:42 MainThread:8668332736 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第1次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 21:03:42 MainThread:8668332736 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第2次重连 'MySocket' object has no attribute 'socekt'
2023-04-19 21:03:42 MainThread:8668332736 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:69] 连接服务器失败，开始第3次重连 'MySocket' object has no attribute 'socekt'
2023-05-02 20:16:24 Dummy-1:12999159808 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:16:26 Dummy-1:12999159808 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-02 20:16:28 Dummy-1:12999159808 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-05-02 20:17:05 Dummy-1:13009444864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:17:36 Dummy-1:13009444864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:19:02 MainThread:8609891008 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:19:04 MainThread:8609891008 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-02 20:19:06 MainThread:8609891008 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-05-02 20:21:28 MainThread:8662635200 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:21:30 MainThread:8662635200 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-02 20:21:32 MainThread:8662635200 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-05-02 20:21:39 Dummy-1:13072461824 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:21:41 Dummy-1:13072461824 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-02 20:21:43 Dummy-1:13072461824 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-05-02 20:22:36 MainThread:8602284736 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:22:38 MainThread:8602284736 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-02 20:22:44 Dummy-1:12927119360 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:22:46 Dummy-1:12927119360 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-02 20:22:48 Dummy-1:12927119360 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-05-02 20:33:45 Dummy-1:12919107584 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:33:47 Dummy-1:12919107584 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-02 20:33:49 Dummy-1:12919107584 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-05-02 20:35:59 Dummy-1:12916961280 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:36:01 Dummy-1:12916961280 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-02 20:36:03 Dummy-1:12916961280 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第3次重连 [Errno 61] Connection refused
2023-05-02 20:36:59 Dummy-1:13006729216 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:37:07 Dummy-1:13006729216 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-02 20:39:26 Dummy-1:12917141504 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:71] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:26 Dummy-1:13047484416 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:26 Dummy-1:12931313664 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:34 Dummy-1:13047484416 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:34 Dummy-1:12931313664 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:39 Dummy-1:13047484416 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:39 Dummy-1:12931313664 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:44 Dummy-1:13047484416 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:44 Dummy-1:12931313664 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:50 Dummy-1:12931313664 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:50 Dummy-1:13047484416 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:54 Dummy-1:13047484416 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:05:54 Dummy-1:12931313664 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:11:17 Dummy-1:13047484416 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:11:17 Dummy-1:12923285504 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:11:43 Dummy-1:12923285504 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:11:43 Dummy-1:13047484416 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:12:38 Dummy-1:13047574528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:12:38 Dummy-1:12915650560 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:13:40 Dummy-1:12915650560 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:13:40 Dummy-1:13047574528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:13:44 Dummy-1:12915650560 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:13:44 Dummy-1:13047574528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:16:55 Dummy-1:13045526528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:16:55 Dummy-1:13059944448 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:16:59 Dummy-1:13045526528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:16:59 Dummy-1:13059944448 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:17:03 Dummy-1:13045526528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:17:03 Dummy-1:13059944448 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:17:13 Dummy-1:13059944448 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:17:13 Dummy-1:13045526528 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:18:16 Dummy-1:12996177920 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:18:16 Dummy-1:12909604864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:18:21 Dummy-1:12996177920 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-04 22:18:21 Dummy-1:12909604864 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:70] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-12 14:10:38 MainThread:8627118720 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:93] 连接服务器失败，开始第1次重连 [Errno 61] Connection refused
2023-05-12 14:10:40 MainThread:8627118720 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:93] 连接服务器失败，开始第2次重连 [Errno 61] Connection refused
2023-05-17 23:24:20 Dummy-2:12914503680 [error_logger] ERROR [/Users/fei/teach/chat_room/client/core/client.py:148] 连接服务器失败，开始第1次重连 [Errno 60] Operation timed out
2024-11-24 10:30:53 MainThread:22912 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第1次重连 [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2024-11-24 10:31:16 MainThread:22912 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第2次重连 [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2024-11-24 10:31:39 MainThread:22912 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第3次重连 [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2024-11-24 10:35:22 MainThread:36968 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第1次重连 [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2024-11-24 10:35:45 MainThread:36968 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第2次重连 [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2024-11-24 10:36:05 MainThread:37572 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第1次重连 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-11-24 11:10:08 MainThread:34448 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第1次重连 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-11-24 11:10:12 MainThread:34448 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第2次重连 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2024-11-24 11:10:16 MainThread:34448 [error_logger] ERROR [D:\Desktop\学习\python\client\core\client.py:148] 连接服务器失败，开始第3次重连 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
